# Generated by Django 2.2.3 on 2019-07-06 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('splitwise', '0002_auto_20190706_1848'),
        ('telegram', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
