# Generated by Django 2.2.3 on 2019-07-13 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0002_delete_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='state',
            field=models.CharField(choices=[('MAIN', 'main'), ('GET_FNS_NUMBER', 'get_fns_number'), ('GET_FNS_PASSWORD', 'get_fns_password')], default='main', max_length=128),
        ),
    ]
