# Generated by Django 2.2.3 on 2019-07-06 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('splitwise', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppinglistuser',
            name='message',
        ),
        migrations.AddField(
            model_name='shoppinglistuser',
            name='message_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
