# Generated by Django 2.2.3 on 2019-07-07 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('splitwise', '0002_auto_20190706_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppinglist',
            name='state',
            field=models.CharField(default='main', max_length=128),
        ),
    ]
