# Generated by Django 2.2.3 on 2019-07-13 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('splitwise', '0003_auto_20190707_0144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppinglist',
            name='state',
        ),
        migrations.AlterField(
            model_name='user',
            name='state',
            field=models.CharField(default='main', max_length=128),
        ),
    ]
