# Generated by Django 2.2.3 on 2019-07-14 01:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('splitwise', '0004_auto_20190713_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppinglist',
            name='payer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='splitwise.User'),
        ),
    ]
