# Generated by Django 2.2.3 on 2019-07-14 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('splitwise', '0005_auto_20190714_0111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='count',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
